import type { S3Event, S3EventRecord } from 'aws-lambda';
import {
  TranscribeClient,
  StartTranscriptionJobCommand,
  ConflictException,
} from '@aws-sdk/client-transcribe';
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, PutCommand, UpdateCommand } from '@aws-sdk/lib-dynamodb';

const transcribe = new TranscribeClient({});
const ddb = DynamoDBDocumentClient.from(new DynamoDBClient({}));

const VIDEOS_TABLE = process.env['VIDEOS_TABLE']!;

// Bucket name format: ttv-{clientId}-videos
function parseClientId(bucketName: string): string {
  return bucketName.replace(/^ttv-/, '').replace(/-videos$/, '');
}

// Key format expected from the frontend: {videoId}/{filename}
// The videoId is a UUID pre-generated by the frontend before upload.
function parseVideoId(key: string): string | null {
  const slash = key.indexOf('/');
  if (slash <= 0) return null;
  return key.slice(0, slash);
}

async function processRecord(record: S3EventRecord): Promise<void> {
  const bucket = record.s3.bucket.name;
  // S3 keys can have URL-encoded characters and use + for spaces
  const key = decodeURIComponent(record.s3.object.key.replace(/\+/g, ' '));

  // Skip folders and hidden files
  if (key.endsWith('/') || key.includes('/.')) return;

  const clientId = parseClientId(bucket);
  const videoId = parseVideoId(key);

  if (!videoId) {
    console.warn(`Skipping key with no videoId prefix: ${key}`);
    return;
  }

  const transcriptBucket = `ttv-${clientId}-transcripts`;
  const jobName = `ttv-${videoId}`;
  const now = new Date().toISOString();

  // Register the video. ConditionExpression makes this idempotent:
  // if S3 delivers a duplicate event the second write fails silently.
  try {
    await ddb.send(
      new PutCommand({
        TableName: VIDEOS_TABLE,
        Item: {
          client_id: clientId,
          video_id: videoId,
          status: 'TRANSCRIBING',
          s3_key: key,
          video_bucket: bucket,
          transcribe_job_name: jobName,
          created_at: now,
          updated_at: now,
        },
        ConditionExpression: 'attribute_not_exists(video_id)',
      }),
    );
  } catch (err: unknown) {
    if ((err as { name?: string }).name === 'ConditionalCheckFailedException') {
      console.log(`Video ${videoId} already registered — duplicate S3 event, skipping`);
      return;
    }
    throw err;
  }

  // Start the Transcribe job.
  // OutputKey ends with "/" so Transcribe appends: {videoId}/ttv-{videoId}.json
  // ProcessTranscriptLambda reads videoId from key.split('/')[0].
  try {
    await transcribe.send(
      new StartTranscriptionJobCommand({
        TranscriptionJobName: jobName,
        Media: { MediaFileUri: `s3://${bucket}/${key}` },
        OutputBucketName: transcriptBucket,
        OutputKey: `${videoId}/`,
        LanguageCode: 'en-US',
        Settings: {
          ShowSpeakerLabels: true,
          MaxSpeakerLabels: 10,
          ShowAlternatives: false,
        },
      }),
    );
  } catch (err: unknown) {
    if (err instanceof ConflictException) {
      // Job name already in use — duplicate event handled by DynamoDB above,
      // but Transcribe might have been started before DynamoDB write was idempotent.
      console.log(`Transcribe job ${jobName} already exists, skipping`);
      return;
    }
    // Transcribe failed to start — mark the video so it's not stuck as TRANSCRIBING.
    // UpdateCommand preserves the fields written by the earlier PutCommand.
    await ddb.send(
      new UpdateCommand({
        TableName: VIDEOS_TABLE,
        Key: { client_id: clientId, video_id: videoId },
        UpdateExpression: 'SET #status = :status, #error = :error, updated_at = :now',
        ExpressionAttributeNames: { '#status': 'status', '#error': 'error' },
        ExpressionAttributeValues: {
          ':status': 'ERROR',
          ':error': (err as Error).message,
          ':now': new Date().toISOString(),
        },
      }),
    );
    throw err;
  }

  console.log(`Started Transcribe job ${jobName} for client ${clientId}, video ${videoId}`);
}

export const handler = async (event: S3Event): Promise<void> => {
  for (const record of event.Records) {
    try {
      await processRecord(record);
    } catch (err) {
      // Log and continue — don't let one bad record block the others
      console.error('Failed to process S3 record:', JSON.stringify(record.s3), err);
    }
  }
};
